export const DATAKECAMATAN = [
    " PILIH",
    "Bonang",
    "Demak",
    "Dempet",
    "Gajah",
    "Guntur",
    "Karanganyar",
    "Karangawen",
    "Karangtengah",
    "Kebonagung",
    "Mijen",
    "Mranggen",
    "Sayung",
    "Wedung",
    "Wonosalam",
  ];

export const Bonang = [
  "Bonangrejo",
  "Gebang",
  "Gebangarum",
  "Jali",
  "Jatimulyo",
  "Jatirogo",
  "Karangrejo",
  "Kembangan",
  "Krajanbogo",
  "Margolinduk",
  "Morodemak",
  "Poncoharjo",
  "Purworejo",
  "Serangan",
  "Sukodono",
  "Sumberejo",
  "Tlogoboyo",
  "Tridonorejo",
  "Weding",
  "Wonosari",
];

export const Demak = [
  "Bolo",
  "Cabean",
  "Donorejo",
  "Kalikondang",
  "Karangmlati",
  "Katonsari",
  "Kedondong",
  "Mulyorejo",
  "Raji",
  "Sedo",
  "Tempuran",
  "Turirejo",
  "Betokan",
  "Bintoro",
  "Kadilangu",
  "Kalicilik",
  "Mangunjiwan",
  "Singorejo",
];

export const Dempet = [
  "Baleromo",
  "Botosengon",
  "Brakas",
  "Dempet",
  "Gempoldenok",
  "Harjowinangun",
  "Jerukgulung",
  "Karangrejo",
  "Kebonsari",
  "Kedungori",
  "Kramat",
  "Kunir",
  "Kuwu",
  "Merak",
  "Sidomulyo",
];
export const Gajah = [
  "Boyolali",
  "Gajah",
  "Gedangalas",
  "Jatisono",
  "Kedondong",
  "Medini",
  "Mlatiharjo",
  "Mlekang",
  "Mojosimo",
  "Sambiroto",
  "Sambung",
  "Sari",
  "Surodadi",
  "Tambirejo",
  "Tanjunganyar",
  "Tlogopandogan",
  "Wilalung",
];

export const Guntur = [
  "Banjarejo",
  "Blerong",
  "Bogosari",
  "Bumiharjo",
  "Gaji",
  "Guntur",
  "Krandon",
  "Pamongan",
  "Sarirejo",
  "Sidoharjo",
  "Sidokumpul",
  "Sukorejo",
  "Tangkis",
  "Temuroso",
  "Tlogorejo",
  "Tlogoweru",
  "Trimulyo",
  "Turitempel",
  "Wonorejo",
];
export const Karanganyar = [
  "Cangkring",
  "Cangkring Rembang",
  "Jatirejoo",
  "Karanganyar",
  "Kedungwaru Kidul",
  "Kedungwaru Lor",
  "Ketanjung",
  "Kotakan",
  "Ngaluran",
  "Ngemplik Wetan",
  "Tugu Lor",
  "Tuwang",
  "Undaan Kidul",
  "Undaan Lor",
  "Wonoketingal",
  "Wonorejo",
];
export const Karangawen = [
  "Bumirejo",
  "Jragung",
  "Karangawen",
  "Kuripan",
  "Margohayu",
  "Pundenarum",
  "Rejosari",
  "Sido Rejo",
  "Teluk",
  "Tlogorejo",
  "Wonosekar",
];
export const Karangtengah = [
  "Donorejo",
  "Dukun",
  "Grogol",
  "Karangsari",
  "Karangtowo",
  "Kedunguter",
  "Klitih",
  "Pidodo",
  "Ploso",
  "Pulosari",
  "Rejosari",
  "Sampang",
  "Tambakbulusan",
  "Wonoagung",
  "Wonokerto",
  "Wonowoso",
];
export const Kebonagung = [
  "Kebonagung",
  "Klampok Lor",
  "Mangunan Lor",
  "Mangunrejo",
  "Megonten",
  "Mijen",
  "Pilangwetan",
  "Prigi",
  "Sarimulyo",
  "Soko Kidul",
  "Solowire",
  "Tlogosih",
  "Werdoyo",
];
export const Mijen = [
  "Banteng Mati",
  "Bermi",
  "Gempolsongo",
  "Geneng",
  "Jleper",
  "Mijen",
  "Mlaten",
  "Ngegot",
  "Ngelo Kulon",
  "Ngelo Wetan",
  "Pasir",
  "Pecuk",
  "Rejosari",
  "Tanggul",
];
export const Mranggen = [
  "Banyumeneng",
  "Batursari",
  "Brumbung",
  "Candisari",
  "Jamus",
  "Kalitengah",
  "Kangkung",
  "Karangsono",
  "Kebonbatur",
  "Kembangarum",
  "Menur",
  "Mranggen",
  "Ngemplak",
  "Sumberejo",
  "Tamansari",
  "Tegalarum",
  "Waru",
  "Wringin Jajar",
];
export const Sayung = [
  "Bedono",
  "Bulusari",
  "Dombo",
  "Gemulak",
  "Jetaksari",
  "Kalisari",
  "Karangasem",
  "Loireng",
  "Perampelan",
  "Pilangsari",
  "Purwosari",
  "Sayung",
  "Sidogemah",
  "Sidorejo",
  "Sriwulan",
  "Surodadi",
  "Tambakroto",
  "Timbulsloko",
  "Tugu",
];
export const Wedung = [
  "Berahan Kulon",
  "Berahan Wetan",
  "Buko",
  "Bungo",
  "Jetak",
  "Jungpasir",
  "Jungsemi",
  "Kedungkarang",
  "Kedungmutih",
  "Kendalasem",
  "Kenduren",
  "Mandung",
  "Mutih Kulon",
  "Mutih Wetan",
  "Ngawen",
  "Ruwit",
  "Tedunan",
  "Tempel",
  "Wedung",
];
export const Wonosalam = [
  "Bunderan",
  "Doreng",
  "Getas",
  "Jogoloyo",
  "Kalianyar",
  "Karangrejo",
  "Karangrowo",
  "Kendaldoyong",
  "Kerangkulon",
  "Kuncir",
  "Lempuyang",
  "Mojodemak",
  "Mranak",
  "Mrisen",
  "Pilangrejo",
  "Sido Mulyo",
  "Tlogodowo",
  "Tlogorejo",
  "Trengguli",
  "Wonosalam",
];
